// <auto-generated />
using System;
using EventsPortal.DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EventsPortal.DAL.Migrations
{
    [DbContext(typeof(EventsPortalDbContext))]
    [Migration("20200212162233_Initial-Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EventsPortal.DAL.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int>("EventTypeId");

                    b.Property<string>("Note");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("EventTypeId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2019, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque id nibh non mauris efficitur fringilla. Ut vitae nisi sed ipsum vestibulum vestibulum. Vestibulum nibh eros, varius eget nisl eu, scelerisque malesuada enim. Vivamus gravida lacus tortor, vitae rutrum nisl condimentum vel. Sed mollis justo vitae rhoncus feugiat. Cras faucibus, odio at dapibus maximus, lacus nunc vestibulum lectus, sit amet aliquet neque augue sed purus. Mauris lobortis finibus vulputate. Fusce pellentesque maximus tempus. Curabitur ullamcorper dictum enim, ut venenatis tellus sodales sit amet",
                            EventTypeId = 1,
                            Note = "Proin molestie ligula nunc, et rutrum turpis porta et. Nulla purus quam, iaculis non quam vel, pellentesque tincidunt augue. Morbi accumsan ac sapien et tempor. Phasellus ex sem, faucibus posuere ultricies eu, aliquam a quam. Aenean convallis cursus ipsum, vel laoreet nisl blandit in. Curabitur condimentum velit et quam interdum, imperdiet pharetra orci consectetur. Cras tempor auctor tincidunt. Etiam id nulla sit amet diam posuere lobortis. Vestibulum vel urna a mauris elementum rutrum. Praesent venenatis maximus hendrerit. Pellentesque at lacus sit amet massa mattis iaculis sit amet sit amet nisi. Nulla consectetur elit vitae felis sodales, id bibendum odio convallis. Aenean aliquet, tortor non fermentum molestie, metus est tincidunt nibh, a faucibus arcu turpis in tortor. Ut molestie ullamcorper placerat",
                            Title = "Event 1"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2019, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Curabitur ullamcorper odio at feugiat vulputate. Maecenas sed lacinia lectus, sed imperdiet ex. Mauris commodo sollicitudin lectus molestie tempus. Cras rutrum nisl purus, vitae cursus sem convallis rhoncus. In leo metus, molestie nec sagittis nec, congue eget felis. Pellentesque feugiat diam eu dolor pellentesque congue. Nunc tristique varius suscipit. Proin fringilla vehicula enim, eu placerat nunc iaculis ut. Nunc eu ligula et erat sagittis tincidunt quis laoreet sapien. Quisque scelerisque dolor et augue lobortis, nec pellentesque felis varius.",
                            EventTypeId = 2,
                            Note = "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec rutrum non sapien ut fermentum. Mauris in velit tellus. Praesent sodales ipsum quis turpis porttitor, non efficitur tortor consectetur. Integer iaculis tempor purus. Sed eget eros sed dui faucibus feugiat eget ut nibh. In luctus velit libero, eget sagittis eros condimentum non. Suspendisse potenti. Vivamus gravida fringilla ornare. Duis pellentesque nec ante vehicula pharetra. Morbi ac neque in risus laoreet ullamcorper. Fusce facilisis ullamcorper eros non molestie. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos",
                            Title = "Event 2"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2019, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Maecenas euismod consequat viverra. Duis et dignissim nisl, sodales cursus tortor. Proin pulvinar ante neque, sed aliquam neque lacinia a. Quisque ultrices convallis neque eu finibus. Integer libero ante, semper ut ante euismod, rhoncus imperdiet tortor. Mauris pretium scelerisque justo et pellentesque. Aliquam finibus ligula libero, eget tristique magna pulvinar sed",
                            EventTypeId = 3,
                            Note = "Suspendisse ultricies euismod elit egestas tempor. Sed lobortis neque felis, id egestas nibh dictum a. Phasellus molestie risus sed sem maximus tempus. Fusce sit amet lorem a neque suscipit luctus eget ut mauris. Morbi ac ex orci. Nulla diam risus, ullamcorper eu sapien vel, pretium imperdiet ipsum. Vestibulum ac vehicula mauris, quis maximus nibh. Curabitur ut mauris sapien. Vestibulum pretium scelerisque elit, mollis commodo nibh accumsan eu. Vestibulum at elit nunc. Aliquam eu tortor orci. Nullam venenatis, sapien vel lobortis consectetur, ante nibh egestas augue, non hendrerit felis diam ut metus.",
                            Title = "Event 3"
                        });
                });

            modelBuilder.Entity("EventsPortal.DAL.Models.EventType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Title")
                        .HasMaxLength(50);

                    b.HasKey("TypeId");

                    b.ToTable("EventTypes");

                    b.HasData(
                        new
                        {
                            TypeId = 1,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque id nibh non mauris efficitur fringilla. Ut vitae nisi sed ipsum vestibulum vestibulum. Vestibulum nibh eros, varius eget nisl eu, scelerisque malesuada enim. Vivamus gravida lacus tortor, vitae rutrum nisl condimentum vel. Sed mollis justo vitae rhoncus feugiat. Cras faucibus, odio at dapibus maximus, lacus nunc vestibulum lectus, sit amet aliquet neque augue sed purus. Mauris lobortis finibus vulputate. Fusce pellentesque maximus tempus. Curabitur ullamcorper dictum enim, ut venenatis tellus sodales sit amet",
                            Title = "EventType 1"
                        },
                        new
                        {
                            TypeId = 2,
                            Description = "Curabitur ullamcorper odio at feugiat vulputate. Maecenas sed lacinia lectus, sed imperdiet ex. Mauris commodo sollicitudin lectus molestie tempus. Cras rutrum nisl purus, vitae cursus sem convallis rhoncus. In leo metus, molestie nec sagittis nec, congue eget felis. Pellentesque feugiat diam eu dolor pellentesque congue. Nunc tristique varius suscipit. Proin fringilla vehicula enim, eu placerat nunc iaculis ut. Nunc eu ligula et erat sagittis tincidunt quis laoreet sapien. Quisque scelerisque dolor et augue lobortis, nec pellentesque felis varius.",
                            Title = "EventType 2"
                        },
                        new
                        {
                            TypeId = 3,
                            Description = "Maecenas euismod consequat viverra. Duis et dignissim nisl, sodales cursus tortor. Proin pulvinar ante neque, sed aliquam neque lacinia a. Quisque ultrices convallis neque eu finibus. Integer libero ante, semper ut ante euismod, rhoncus imperdiet tortor. Mauris pretium scelerisque justo et pellentesque. Aliquam finibus ligula libero, eget tristique magna pulvinar sed",
                            Title = "EventType 3"
                        });
                });

            modelBuilder.Entity("EventsPortal.DAL.Models.Event", b =>
                {
                    b.HasOne("EventsPortal.DAL.Models.EventType", "EventType")
                        .WithMany("Events")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
